# Understanding `fit_generator`

In [32]:
import numpy as np
import os, random
from tqdm import tqdm
import os
import keras
from keras.applications.inception_v3 import InceptionV3, preprocess_input
from keras.models import Model
from keras.layers import Dense, GlobalAveragePooling2D
from keras.preprocessing.image import ImageDataGenerator
from keras.optimizers import SGD
from keras.datasets import cifar10, mnist

In [34]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
y_train = keras.utils.to_categorical(y_train, 10)
y_test = keras.utils.to_categorical(y_test, 10)

datagen = ImageDataGenerator(
    featurewise_center=True,
    featurewise_std_normalization=True,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True)

# compute quantities required for featurewise normalization
# (std, mean, and principal components if ZCA whitening is applied)
x_train = x_train.reshape([60000, 28, 28, 1])
datagen.fit(x_train)

In [35]:
gen = datagen.flow(x_train, y_train, batch_size=32)

In [36]:
type(gen)

keras.preprocessing.image.NumpyArrayIterator

In [37]:
x = next(gen)

In [40]:
len(x[0])

32

In [46]:
x[0].shape

(32, 28, 28, 1)

In [52]:
x[1]

array([[ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.

In [59]:
from numpy.random import randint
from numpy import argmax
from keras.utils.np_utils import to_categorical
k = 20
n = 20
x = randint(0, k, (n,))
print(x)
print(argmax(to_categorical(x, k)))

[ 5  7 13  9  3 17 16 13 14 18 18  1 12 18  1 11 15 16  4 18]
5


In [74]:
num_classes = 3
y_train = ['cat', 'cat', 'dog', 'chicken', 'cat', 'chicken', 'dog']

In [77]:
from sklearn.preprocessing import LabelBinarizer

encoder = LabelBinarizer()
y_train_encoded = encoder.fit_transform(y_train)
print(y_train_encoded)

[[1 0 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]]


In [78]:
y_predicted = [0.1, 0.1, 0.8]

In [84]:
encoder.classes_[argmax(y_predicted)]
#encoder.inverse_transform(argmax(y_predicted))

'dog'